version: '3'
services:
  astroparticle:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ap_container
    runtime: nvidia
    volumes:
      - ..:/usr/local/python/astroparticle
    # this does not work.
    command: pip install -e /usr/local/python/astroparticle
    ports:
      - 8080:80
