"""Transition function library.
"""
from partical_xspec.transition import util
from partical_xspec.transition.local_linear_trend import get_transition_function_local_linear_trend
from partical_xspec.transition.trend import get_transition_function_trend
from partical_xspec.transition.vector_autoregressive import get_transition_function_var
from partical_xspec.transition.vector_autoregressive import get_proposal_function_var
from partical_xspec.transition.vector_autoregressive import VectorAutoregressiveTransition
