"""Observation class."""
from astroparticle.python.experimental.observations import xray_spectrum
from astroparticle.python.experimental.observations.observation import ObservationModel
from astroparticle.python.experimental.observations.xray_spectrum.binning import Rebin
from astroparticle.python.experimental.observations.xray_spectrum.response import CustumResponseModel
from astroparticle.python.experimental.observations.xray_spectrum.response_satellite import ResponseNicerXti
from astroparticle.python.experimental.observations.xray_spectrum.response_satellite import ResponseXrismResolve
from astroparticle.python.experimental.observations.xray_spectrum.components.powerlaw import PowerLaw
from astroparticle.python.experimental.observations.xray_spectrum.components.diskbb import DiskBB
from astroparticle.python.experimental.observations.xray_spectrum.components.diskpbb import DiskPBB
from astroparticle.python.experimental.observations.xray_spectrum.components.gauss import Gauss
from astroparticle.python.experimental.observations.xray_spectrum.components.physical_component import PhysicalComponent
